name: Release Chrome Extension

permissions:
  contents: write

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build and package extension
        run: npm run package
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            chrome-extension.zip
          generate_release_notes: true